name: dealii-real

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 1200
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: adamqc/dealii-real
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with petsc@real
        uses: docker/build-push-action@v5
        with:
          context: ./dealii-real
          push: true
          tags: ${{ steps.meta.outputs.tags }}
